n = (input('Digite algo: '))
print(n, 'É do tipo primitivo: ', type(n))
print(n,'Só tem espaços?:', n.isspace())
print(n,'É um número:', n.isnumeric())
print(n,'É alfabético?:', n.isalpha())
print(n,'É alfanumérico?:', n.isalnum())
print(n,'Está em maiúsculas?:', n.isupper())
print(n,'Está em minúsculas?:', n.islower())
print(n,'Está capitalizada?:', n.istitle())